# Generated by Django 5.0.6 on 2024-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.CharField(default='not available', max_length=40),
        ),
    ]
