# Generated by Django 5.0.6 on 2024-09-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_student_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comments',
        ),
    ]
